enum UI {  
  TOGGLE_IS_ACTIVE = 'UI/INAV/TOGGLE_IS_ACTIVE',
  CLOSE_INAV = 'UI/INAV/CLOSE_INAV',
  CANCEL = 'UI/INAV/CANCEL',
  INCREMENT = 'UI/INAV/INCREMENT',
  DECREMENT = 'UI/INAV/DECREMENT',
  SWITCH_PAGE_FORWARD = 'UI/INAV/SWITCH_PAGE_FORWARD',
  SWITCH_PAGE_BACK = 'UI/INAV/SWITCH_PAGE_BACK'
  
}

export { UI }