enum INAV {
  // Query
  FETCH_QUERY_REQUEST = 'INAV/FETCH_QUERY_REQUEST',
  FETCH_QUERY_SUCCESS = 'INAV/FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE = 'INAV/FETCH_QUERY_FAILURE',
}

enum ASPECT {
  // Query
  FETCH_QUERY_REQUEST = 'INAV/ASPECT/FETCH_QUERY_REQUEST',
  FETCH_QUERY_SUCCESS = 'INAV/ASPECT/FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE = 'INAV/ASPECT/FETCH_QUERY_FAILURE',
}

enum REFINEMENT {
  // Query
  FETCH_QUERY_REQUEST = 'INAV/REFINEMENT/FETCH_QUERY_REQUEST',
  FETCH_QUERY_SUCCESS = 'INAV/REFINEMENT/FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE = 'INAV/REFINEMENT/FETCH_QUERY_FAILURE',
}


export { INAV, ASPECT, REFINEMENT }