enum INAV { 
    UPDATE_PENDING_ACTION = 'INAV/UPDATE_PENDING_ACTION',
    UPDATE_PREVIOUS_STATE = 'INAV/UPDATE_PREVIOUS_STATE',
    ADD_PROMOTED_ARTICLE = 'ADD_PROMOTED_ARTICLE',
    EMIT_NATIVE_ADS_EVENT = 'EMIT_NATIVE_ADS_EVENT'
}

export { INAV }