enum CAROUSEL {
  // Query
  FETCH_QUERY_REQUEST = 'CAROUSEL/FETCH_QUERY_REQUEST',
  FETCH_QUERY_SUCCESS = 'CAROUSEL/FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE = 'CAROUSEL/FETCH_QUERY_FAILURE',
}

export { CAROUSEL }